#include "Basic_defines.h"
#include "NRPyEOS.h"
#include "NRPyLeakage.h"

/*
 * (c) Leo Werneck
 * Compute GRMHD source terms following Ruffert et al. (1996)
 * https://adsabs.harvard.edu/pdf/1996A%26A...311..532R
 */
void NRPyLeakage_compute_GRMHD_source_terms_and_opacities_nrpy_constants(const NRPyEOS_params *restrict eos_params,
                                                                         const REAL rho_b,
                                                                         const REAL Y_e,
                                                                         const REAL T,
                                                                         const REAL *restrict tau_nue,
                                                                         const REAL *restrict tau_anue,
                                                                         const REAL *restrict tau_nux,
                                                                         REAL *restrict R_source,
                                                                         REAL *restrict Q_source,
                                                                         REAL *restrict kappa_nue,
                                                                         REAL *restrict kappa_anue,
                                                                         REAL *restrict kappa_nux) {


  // Step 1: Get chemical potentials and mass
  //         fractions using the EOS
  REAL mu_e, mu_p, mu_n, muhat, X_p, X_n;
  NRPyEOS_mue_mup_mun_muhat_Xn_and_Xp_from_rho_Ye_T(eos_params, rho_b, Y_e, T,
                                                    &mu_e, &mu_p, &mu_n, &muhat, &X_p, &X_n);

  // Step 2: Compute rho_b in cgs units
  const REAL rho_b_cgs = rho_b * NRPyLeakage_units_geom_to_cgs_D;

/* Leo says: this is the way ZelmaniLeak computes Y_pn and Y_np
  // Step 3: Compute Y_{pn} and Y_{np}
  // Step 3.a: Compute Y_{pn} (See discussion below Eq. A8 in https://arxiv.org/pdf/1306.4953.pdf)
  const REAL Y_p = Y_e;
  const REAL Y_n = 1-Y_e;
  REAL Y_pn;
  if( rho_b_cgs > 2e12 ) {
    // Step 3.a.i: Use Eqs. (A13) and (A14) in https://adsabs.harvard.edu/pdf/1996A%26A...311..532R
    Y_pn = (2*Y_e - 1)/(1-exp(muhat/T));
  }
  else {
    Y_pn = Y_n;
  }
  // Step 3.a.ii: Make sure Y_{pn} is nonzero
  Y_pn = MAX(Y_pn,0.0);

  // Step 3.b: Compute Y_{np} (Eq. A13 in https://adsabs.harvard.edu/pdf/1996A%26A...311..532R)
  const REAL Y_np = exp(muhat/T) * Y_pn;
*/

  // Step 3: Compute Y_{pn} and Y_{np}
  const REAL Y_p = Y_e;
  const REAL Y_n = 1-Y_e;
  const REAL exp_metahat = exp(-muhat/T);
  // Step 3.a: Compute Y_{np}
  REAL Y_np = (Y_e < 0.5) ? (2.0*Y_e-1.0)/(exp_metahat-1.0) : Y_n;

  // Step 3.b: Compute Y_{pn}
  REAL Y_pn = (Y_e > 0.5) ? exp_metahat*(2.0*Y_e-1.0)/(exp_metahat-1.0) : Y_p;

  // Step 3.c: Make sure both Y_np and Y_pn are non-negative
  if( Y_np < 0.0 ) Y_np = Y_n;
  if( Y_pn < 0.0 ) Y_pn = Y_p;

  // Step 4: Compute the source terms
  //         Note: The code below is generated by NRPy+

  REAL R_beta_nue,R_beta_anue,R_pair_nue_anue,R_pair_nux_anux,R_plasmon_nue_anue,R_plasmon_nux_anux,R_Brems_nui_anui;
  REAL Q_beta_nue,Q_beta_anue,Q_pair_nue_anue,Q_pair_nux_anux,Q_plasmon_nue_anue,Q_plasmon_nux_anux,Q_Brems_nui_anui;
  REAL R_eff_nue,R_eff_anue,Q_eff_nue,Q_eff_anue,Q_eff_nux;
  REAL kappa_s_n_0_nue,kappa_s_p_0_nue,kappa_a_0_nue,kappa_s_n_1_nue,kappa_s_p_1_nue,kappa_a_1_nue;
  REAL kappa_s_n_0_anue,kappa_s_p_0_anue,kappa_a_0_anue,kappa_s_n_1_anue,kappa_s_p_1_anue,kappa_a_1_anue;
  REAL kappa_s_n_0_nux,kappa_s_p_0_nux,kappa_s_n_1_nux,kappa_s_p_1_nux;
  const REAL tmp_0 = (1.0/(T));
  const REAL tmp_1 = mu_e*tmp_0;
  const REAL tmp_2 = NRPyLeakage_Fermi_Dirac_integrals(4, tmp_1);
  const REAL tmp_3 = NRPyLeakage_Fermi_Dirac_integrals(5, tmp_1)/tmp_2;
  const REAL tmp_5 = -muhat*tmp_0 + tmp_1;
  const REAL tmp_6 = ((NRPyLeakage_alpha)*(NRPyLeakage_alpha));
  const REAL tmp_7 = M_PI/NRPyLeakage_hc3;
  const REAL tmp_9 = 8*NRPyLeakage_N_A*NRPyLeakage_beta*((T)*(T)*(T)*(T)*(T))*rho_b_cgs*tmp_7*((3.0/8.0)*tmp_6 + 1.0/8.0);
  const REAL tmp_10 = NRPyLeakage_enable_beta_nue*EnsureFinite(Y_pn*tmp_2*tmp_9/(exp(-tmp_3 + tmp_5) + 1));
  const REAL tmp_12 = NRPyLeakage_Fermi_Dirac_integrals(4, -tmp_1);
  const REAL tmp_13 = NRPyLeakage_Fermi_Dirac_integrals(5, -tmp_1)/tmp_12;
  const REAL tmp_14 = muhat*tmp_0 - tmp_1;
  const REAL tmp_15 = NRPyLeakage_enable_beta_anue*EnsureFinite(Y_np*tmp_12*tmp_9/(exp(-tmp_13 + tmp_14) + 1));
  const REAL tmp_16 = NRPyLeakage_Fermi_Dirac_integrals(3, tmp_1);
  const REAL tmp_17 = (1.0/(tmp_16));
  const REAL tmp_18 = NRPyLeakage_Fermi_Dirac_integrals(3, -tmp_1);
  const REAL tmp_19 = (1.0/(tmp_18));
  const REAL tmp_20 = -1.0/2.0*tmp_12*tmp_19 - 1.0/2.0*tmp_17*tmp_2;
  const REAL tmp_21 = ((M_PI)*(M_PI));
  const REAL tmp_23 = (1.0/((NRPyLeakage_hc3)*(NRPyLeakage_hc3)));
  const REAL tmp_24 = tmp_16*tmp_21*tmp_23;
  const REAL tmp_25 = pow(T, 8);
  const REAL tmp_27 = (16.0/9.0)*NRPyLeakage_beta*tmp_18*tmp_24*tmp_25;
  const REAL tmp_28 = NRPyLeakage_enable_pair_nue_anue*EnsureFinite(NRPyLeakage_C1pC2_nue_anue*tmp_27/((exp(tmp_14 + tmp_20) + 1)*(exp(tmp_20 + tmp_5) + 1)));
  const REAL tmp_29 = NRPyLeakage_enable_pair_nux_anux*EnsureFinite(NRPyLeakage_C1pC2_nux_anux*tmp_27/((exp(tmp_20) + 1)*(exp(tmp_20) + 1)));
  const REAL tmp_31 = (1.0/3.0)*tmp_21 + ((mu_e)*(mu_e))/((T)*(T));
  const REAL tmp_32 = NRPyLeakage_gamma_0*sqrt(tmp_31);
  const REAL tmp_34 = ((NRPyLeakage_gamma_0)*(NRPyLeakage_gamma_0))*tmp_31/(tmp_32 + 1);
  const REAL tmp_35 = -1.0/2.0*tmp_34 - 1;
  const REAL tmp_36 = (1.0/3.0)*((M_PI)*(M_PI)*(M_PI))*NRPyLeakage_beta*pow(NRPyLeakage_gamma_0, 6)*tmp_23*tmp_25*((tmp_31)*(tmp_31)*(tmp_31))*(tmp_32 + 1)*exp(-tmp_32)/NRPyLeakage_alpha_fs;
  const REAL tmp_37 = NRPyLeakage_enable_plasmon_nue_anue*EnsureFinite(((NRPyLeakage_C_V)*(NRPyLeakage_C_V))*tmp_36/((exp(tmp_14 + tmp_35) + 1)*(exp(tmp_35 + tmp_5) + 1)));
  const REAL tmp_38 = ((NRPyLeakage_C_V - 1)*(NRPyLeakage_C_V - 1));
  const REAL tmp_39 = NRPyLeakage_enable_plasmon_nux_anux*EnsureFinite(tmp_36*tmp_38/((exp(tmp_35) + 1)*(exp(tmp_35) + 1)));
  const REAL tmp_40 = NRPyLeakage_enable_brems_nui_anui*EnsureFinite(NRPyLeakage_Brems_C1*NRPyLeakage_Brems_zeta*pow(T, 4.5)*rho_b_cgs*(((X_n)*(X_n)) + (28.0/3.0)*X_n*X_p + ((X_p)*(X_p))));
  const REAL tmp_41 = EnsureFinite(T*tmp_10*tmp_3);
  const REAL tmp_42 = EnsureFinite(T*tmp_13*tmp_15);
  const REAL tmp_43 = 32*pow(T, 9);
  const REAL tmp_44 = (1.0/64.0)*((NRPyLeakage_hc3)*(NRPyLeakage_hc3))*tmp_17*tmp_19*(tmp_12*tmp_24*tmp_43 + tmp_18*tmp_2*tmp_21*tmp_23*tmp_43)/(tmp_21*tmp_25);
  const REAL tmp_45 = EnsureFinite(tmp_28*tmp_44);
  const REAL tmp_46 = EnsureFinite(tmp_29*tmp_44);
  const REAL tmp_47 = (1.0/2.0)*T*(tmp_34 + 2);
  const REAL tmp_48 = EnsureFinite(tmp_37*tmp_47);
  const REAL tmp_49 = EnsureFinite(tmp_39*tmp_47);
  const REAL tmp_50 = EnsureFinite(NRPyLeakage_Brems_C2*T*tmp_40/NRPyLeakage_Brems_C1);
  const REAL tmp_51 = tmp_28 + tmp_37 + tmp_40;
  const REAL tmp_53 = NRPyLeakage_Fermi_Dirac_integrals(2, tmp_5);
  const REAL tmp_54 = NRPyLeakage_Fermi_Dirac_integrals(4, tmp_5);
  const REAL tmp_55 = NRPyLeakage_N_A*NRPyLeakage_sigma_0*((T)*(T))*rho_b_cgs/((NRPyLeakage_m_e_c2)*(NRPyLeakage_m_e_c2));
  const REAL tmp_56 = tmp_54*tmp_55/tmp_53;
  const REAL tmp_58 = (1 - Y_e)*((5.0/24.0)*tmp_6 + 1.0/24.0)/((2.0/3.0)*MAX(mu_n*tmp_0, 0) + 1);
  const REAL tmp_59 = EnsureFinite(tmp_56*tmp_58);
  const REAL tmp_60 = Y_e*((1.0/6.0)*tmp_38 + (5.0/24.0)*tmp_6)/((2.0/3.0)*MAX(mu_p*tmp_0, 0) + 1);
  const REAL tmp_61 = EnsureFinite(tmp_56*tmp_60);
  const REAL tmp_62 = NRPyLeakage_Fermi_Dirac_integrals(5, tmp_5);
  const REAL tmp_63 = (3.0/4.0)*tmp_6 + 1.0/4.0;
  const REAL tmp_64 = Y_np*tmp_63/(exp(tmp_1 - tmp_62/tmp_54) + 1);
  const REAL tmp_65 = EnsureFinite(tmp_56*tmp_64);
  const REAL tmp_66 = tmp_59 + tmp_61 + tmp_65;
  const REAL tmp_68 = 4*((T)*(T)*(T))*tmp_7;
  const REAL tmp_69 = 6/NRPyLeakage_units_geom_to_cgs_L;
  const REAL tmp_70 = (tmp_10 + tmp_51)/(((tau_nue[0])*(tau_nue[0]))*tmp_69*(tmp_10 + tmp_51)/(tmp_66*MAX(tmp_53*tmp_68, 1.0000000000000001e-15)) + 1);
  const REAL tmp_72 = NRPyLeakage_Fermi_Dirac_integrals(2, tmp_14);
  const REAL tmp_73 = NRPyLeakage_Fermi_Dirac_integrals(4, tmp_14);
  const REAL tmp_74 = tmp_73/tmp_72;
  const REAL tmp_76 = EnsureFinite(tmp_55*tmp_58*tmp_74);
  const REAL tmp_77 = tmp_55*tmp_60;
  const REAL tmp_78 = EnsureFinite(tmp_74*tmp_77);
  const REAL tmp_79 = NRPyLeakage_Fermi_Dirac_integrals(5, tmp_14);
  const REAL tmp_80 = Y_pn*tmp_63/(exp(-tmp_1 - tmp_79/tmp_73) + 1);
  const REAL tmp_81 = EnsureFinite(tmp_55*tmp_74*tmp_80);
  const REAL tmp_82 = tmp_76 + tmp_78 + tmp_81;
  const REAL tmp_83 = (tmp_15 + tmp_51)/(((tau_anue[0])*(tau_anue[0]))*tmp_69*(tmp_15 + tmp_51)/(tmp_82*MAX(tmp_68*tmp_72, 1.0000000000000001e-15)) + 1);
  const REAL tmp_84 = tmp_45 + tmp_48 + tmp_50;
  const REAL tmp_86 = NRPyLeakage_Fermi_Dirac_integrals(3, tmp_5);
  const REAL tmp_87 = tmp_62/tmp_86;
  const REAL tmp_89 = EnsureFinite(tmp_55*tmp_58*tmp_87);
  const REAL tmp_90 = EnsureFinite(tmp_77*tmp_87);
  const REAL tmp_91 = EnsureFinite(tmp_55*tmp_64*tmp_87);
  const REAL tmp_92 = tmp_89 + tmp_90 + tmp_91;
  const REAL tmp_93 = 4*((T)*(T)*(T)*(T))*tmp_7;
  const REAL tmp_94 = tmp_69*(tmp_41 + tmp_84);
  const REAL tmp_95 = (tmp_41 + tmp_84)/(((tau_nue[1])*(tau_nue[1]))*tmp_94/(tmp_92*MAX(tmp_86*tmp_93, 1.0000000000000001e-15)) + 1);
  const REAL tmp_97 = NRPyLeakage_Fermi_Dirac_integrals(3, tmp_14);
  const REAL tmp_98 = tmp_79/tmp_97;
  const REAL tmp_100 = EnsureFinite(tmp_55*tmp_58*tmp_98);
  const REAL tmp_101 = EnsureFinite(tmp_77*tmp_98);
  const REAL tmp_102 = EnsureFinite(tmp_55*tmp_80*tmp_98);
  const REAL tmp_103 = tmp_100 + tmp_101 + tmp_102;
  const REAL tmp_104 = (tmp_42 + tmp_84)/(((tau_anue[1])*(tau_anue[1]))*tmp_69*(tmp_42 + tmp_84)/(tmp_103*MAX(tmp_93*tmp_97, 1.0000000000000001e-15)) + 1);
  const REAL tmp_105 = NRPyLeakage_Fermi_Dirac_integrals(3, 0);
  const REAL tmp_106 = NRPyLeakage_Fermi_Dirac_integrals(5, 0)/tmp_105;
  const REAL tmp_108 = EnsureFinite(tmp_106*tmp_55*tmp_58);
  const REAL tmp_109 = EnsureFinite(tmp_106*tmp_77);
  const REAL tmp_111 = (tmp_46 + tmp_49 + tmp_50)/(((tau_nux[1])*(tau_nux[1]))*tmp_94/((tmp_108 + tmp_109)*MAX(tmp_105*tmp_93, 1.0000000000000001e-15)) + 1);
  const REAL tmp_112 = NRPyLeakage_Fermi_Dirac_integrals(4, 0)/NRPyLeakage_Fermi_Dirac_integrals(2, 0);
  const REAL tmp_113 = EnsureFinite(tmp_112*tmp_55*tmp_58);
  const REAL tmp_114 = EnsureFinite(tmp_112*tmp_77);
  R_beta_nue = tmp_10;
  R_beta_anue = tmp_15;
  R_pair_nue_anue = tmp_28;
  R_pair_nux_anux = tmp_29;
  R_plasmon_nue_anue = tmp_37;
  R_plasmon_nux_anux = tmp_39;
  R_Brems_nui_anui = tmp_40;
  Q_beta_nue = tmp_41;
  Q_beta_anue = tmp_42;
  Q_pair_nue_anue = tmp_45;
  Q_pair_nux_anux = tmp_46;
  Q_plasmon_nue_anue = tmp_48;
  Q_plasmon_nux_anux = tmp_49;
  Q_Brems_nui_anui = tmp_50;
  R_eff_nue = tmp_70;
  R_eff_anue = tmp_83;
  Q_eff_nue = tmp_95;
  Q_eff_anue = tmp_104;
  Q_eff_nux = tmp_111;
  kappa_s_n_0_nue = tmp_59;
  kappa_s_p_0_nue = tmp_61;
  kappa_a_0_nue = tmp_65;
  kappa_s_n_1_nue = tmp_89;
  kappa_s_p_1_nue = tmp_90;
  kappa_a_1_nue = tmp_91;
  kappa_s_n_0_anue = tmp_76;
  kappa_s_p_0_anue = tmp_78;
  kappa_a_0_anue = tmp_81;
  kappa_s_n_1_anue = tmp_100;
  kappa_s_p_1_anue = tmp_101;
  kappa_a_1_anue = tmp_102;
  kappa_s_n_0_nux = tmp_113;
  kappa_s_p_0_nux = tmp_114;
  kappa_s_n_1_nux = tmp_108;
  kappa_s_p_1_nux = tmp_109;
  *R_source = NRPyLeakage_amu*NRPyLeakage_units_cgs_to_geom_R*(-tmp_70 + tmp_83);
  *Q_source = NRPyLeakage_units_cgs_to_geom_Q*(-tmp_104 - 4*tmp_111 - tmp_95);
  kappa_nue[0] = NRPyLeakage_units_geom_to_cgs_L*tmp_66;
  kappa_nue[1] = NRPyLeakage_units_geom_to_cgs_L*tmp_92;
  kappa_anue[0] = NRPyLeakage_units_geom_to_cgs_L*tmp_82;
  kappa_anue[1] = NRPyLeakage_units_geom_to_cgs_L*tmp_103;
  kappa_nux[0] = NRPyLeakage_units_geom_to_cgs_L*(tmp_113 + tmp_114);
  kappa_nux[1] = NRPyLeakage_units_geom_to_cgs_L*(tmp_108 + tmp_109);

  // Step 5: Make sure results are finite; if not reset to small value
  if( !isfinite(*R_source) ) *R_source = 1e-15;
  if( !isfinite(*Q_source) ) *Q_source = 1e-15;
  for(int i=0;i<2;i++) {
    if( !isfinite(kappa_nue [i]) ) kappa_nue [i] = 1e-15;
    if( !isfinite(kappa_anue[i]) ) kappa_anue[i] = 1e-15;
    if( !isfinite(kappa_nux [i]) ) kappa_nux [i] = 1e-15;
  }
  fprintf(stderr,"(NRPyLeakage) R_beta_nue         = %.15e\n",R_beta_nue);
  fprintf(stderr,"(NRPyLeakage) R_beta_anue        = %.15e\n",R_beta_anue);
  fprintf(stderr,"(NRPyLeakage) R_pair_nue_anue    = %.15e\n",R_pair_nue_anue);
  fprintf(stderr,"(NRPyLeakage) R_pair_nux_anux    = %.15e\n",R_pair_nux_anux);
  fprintf(stderr,"(NRPyLeakage) R_plasmon_nue_anue = %.15e\n",R_plasmon_nue_anue);
  fprintf(stderr,"(NRPyLeakage) R_plasmon_nux_anux = %.15e\n",R_plasmon_nux_anux);
  fprintf(stderr,"(NRPyLeakage) R_Brems_nui_anui   = %.15e\n",R_Brems_nui_anui);
  fprintf(stderr,"(NRPyLeakage) Q_beta_nue         = %.15e\n",Q_beta_nue);
  fprintf(stderr,"(NRPyLeakage) Q_beta_anue        = %.15e\n",Q_beta_anue);
  fprintf(stderr,"(NRPyLeakage) Q_pair_nue_anue    = %.15e\n",Q_pair_nue_anue);
  fprintf(stderr,"(NRPyLeakage) Q_pair_nux_anux    = %.15e\n",Q_pair_nux_anux);
  fprintf(stderr,"(NRPyLeakage) Q_plasmon_nue_anue = %.15e\n",Q_plasmon_nue_anue);
  fprintf(stderr,"(NRPyLeakage) Q_plasmon_nux_anux = %.15e\n",Q_plasmon_nux_anux);
  fprintf(stderr,"(NRPyLeakage) Q_Brems_nui_anui   = %.15e\n",Q_Brems_nui_anui);
  fprintf(stderr,"(NRPyLeakage) R_eff_nue          = %.15e\n",R_eff_nue);
  fprintf(stderr,"(NRPyLeakage) R_eff_anue         = %.15e\n",R_eff_anue);
  fprintf(stderr,"(NRPyLeakage) Q_eff_nue          = %.15e\n",Q_eff_nue);
  fprintf(stderr,"(NRPyLeakage) Q_eff_anue         = %.15e\n",Q_eff_anue);
  fprintf(stderr,"(NRPyLeakage) Q_eff_nux          = %.15e\n",Q_eff_nux);
  fprintf(stderr,"(NRPyLeakage) kappa_s_n_0_nue    = %.15e\n",kappa_s_n_0_nue);
  fprintf(stderr,"(NRPyLeakage) kappa_s_p_0_nue    = %.15e\n",kappa_s_p_0_nue);
  fprintf(stderr,"(NRPyLeakage) kappa_a_0_nue      = %.15e\n",kappa_a_0_nue);
  fprintf(stderr,"(NRPyLeakage) kappa_s_n_1_nue    = %.15e\n",kappa_s_n_1_nue);
  fprintf(stderr,"(NRPyLeakage) kappa_s_p_1_nue    = %.15e\n",kappa_s_p_1_nue);
  fprintf(stderr,"(NRPyLeakage) kappa_a_1_nue      = %.15e\n",kappa_a_1_nue);
  fprintf(stderr,"(NRPyLeakage) kappa_s_n_0_anue   = %.15e\n",kappa_s_n_0_anue);
  fprintf(stderr,"(NRPyLeakage) kappa_s_p_0_anue   = %.15e\n",kappa_s_p_0_anue);
  fprintf(stderr,"(NRPyLeakage) kappa_a_0_anue     = %.15e\n",kappa_a_0_anue);
  fprintf(stderr,"(NRPyLeakage) kappa_s_n_1_anue   = %.15e\n",kappa_s_n_1_anue);
  fprintf(stderr,"(NRPyLeakage) kappa_s_p_1_anue   = %.15e\n",kappa_s_p_1_anue);
  fprintf(stderr,"(NRPyLeakage) kappa_a_1_anue     = %.15e\n",kappa_a_1_anue);
  fprintf(stderr,"(NRPyLeakage) kappa_s_n_0_nux    = %.15e\n",kappa_s_n_0_nux);
  fprintf(stderr,"(NRPyLeakage) kappa_s_p_0_nux    = %.15e\n",kappa_s_p_0_nux);
  fprintf(stderr,"(NRPyLeakage) kappa_s_n_1_nux    = %.15e\n",kappa_s_n_1_nux);
  fprintf(stderr,"(NRPyLeakage) kappa_s_p_1_nux    = %.15e\n",kappa_s_p_1_nux);
  fprintf(stderr,"(NRPyLeakage) *R_source          = %.15e\n",*R_source);
  fprintf(stderr,"(NRPyLeakage) *Q_source          = %.15e\n",*Q_source);
  fprintf(stderr,"(NRPyLeakage) kappa_nue[0]       = %.15e\n",kappa_nue[0]);
  fprintf(stderr,"(NRPyLeakage) kappa_nue[1]       = %.15e\n",kappa_nue[1]);
  fprintf(stderr,"(NRPyLeakage) kappa_anue[0]      = %.15e\n",kappa_anue[0]);
  fprintf(stderr,"(NRPyLeakage) kappa_anue[1]      = %.15e\n",kappa_anue[1]);
  fprintf(stderr,"(NRPyLeakage) kappa_nux[0]       = %.15e\n",kappa_nux[0]);
  fprintf(stderr,"(NRPyLeakage) kappa_nux[1]       = %.15e\n",kappa_nux[1]);
  fprintf(stderr,"(NRPyLeakage) ************************************************\n");
}
