#include "Basic_defines.h"
#include "NRPyEOS.h"
#include "NRPyLeakage.h"

/*
 * (c) Leo Werneck
 * Compute GRMHD source terms following Ruffert et al. (1996)
 * https://adsabs.harvard.edu/pdf/1996A%26A...311..532R
 */
void NRPyLeakage_compute_GRMHD_source_terms_and_opacities_nrpy_constants(const NRPyEOS_params *restrict eos_params,
                                                                         const REAL rho_b,
                                                                         const REAL Y_e,
                                                                         const REAL T,
                                                                         const REAL *restrict tau_nue,
                                                                         const REAL *restrict tau_anue,
                                                                         const REAL *restrict tau_nux,
                                                                         REAL *restrict R_source,
                                                                         REAL *restrict Q_source,
                                                                         REAL *restrict kappa_nue,
                                                                         REAL *restrict kappa_anue,
                                                                         REAL *restrict kappa_nux) {


  // Step 1: Get chemical potentials and mass
  //         fractions using the EOS
  REAL mu_e, mu_p, mu_n, muhat, X_p, X_n;
  NRPyEOS_mue_mup_mun_muhat_Xn_and_Xp_from_rho_Ye_T(eos_params,rho_b, Y_e, T,
                                                    &mu_e, &mu_p, &mu_n, &muhat, &X_p, &X_n);

  // Step 2: Compute rho_b in cgs units
  const REAL rho_b_cgs = rho_b * NRPyLeakage_units_geom_to_cgs_D;

/* Leo says: this is the way ZelmaniLeak computes Y_pn and Y_np
  // Step 3: Compute Y_{pn} and Y_{np}
  // Step 3.a: Compute Y_{pn} (See discussion below Eq. A8 in https://arxiv.org/pdf/1306.4953.pdf)
  const REAL Y_p = Y_e;
  const REAL Y_n = 1-Y_e;
  REAL Y_pn;
  if( rho_b_cgs > 2e12 ) {
    // Step 3.a.i: Use Eqs. (A13) and (A14) in https://adsabs.harvard.edu/pdf/1996A%26A...311..532R
    Y_pn = (2*Y_e - 1)/(1-exp(muhat/T));
  }
  else {
    Y_pn = Y_n;
  }
  // Step 3.a.ii: Make sure Y_{pn} is nonzero
  Y_pn = MAX(Y_pn,0.0);
  
  // Step 3.b: Compute Y_{np} (Eq. A13 in https://adsabs.harvard.edu/pdf/1996A%26A...311..532R)
  const REAL Y_np = exp(muhat/T) * Y_pn;
*/

  // Step 3: Compute Y_{pn} and Y_{np}
  const REAL Y_p = Y_e;
  const REAL Y_n = 1-Y_e;
  const REAL exp_metahat = exp(-muhat/T);
  // Step 3.a: Compute Y_{np}
  REAL Y_np = (Y_e < 0.5) ? (2.0*Y_e-1.0)/(exp_metahat-1.0) : Y_n;

  // Step 3.b: Compute Y_{pn}
  REAL Y_pn = (Y_e > 0.5) ? exp_metahat*(2.0*Y_e-1.0)/(exp_metahat-1.0) : Y_p;

  // Step 3.c: Make sure both Y_np and Y_pn are non-negative
  if( Y_np < 0.0 ) Y_np = Y_n;
  if( Y_pn < 0.0 ) Y_pn = Y_p;

  // Step 4: Compute the source terms
  //         Note: The code below is generated by NRPy+

  REAL R_beta_nue,R_beta_anue,R_pair_nue_anue,R_pair_nux_anux,R_plasmon_nue_anue,R_plasmon_nux_anux,R_Brems_nui_anui;
  REAL Q_beta_nue,Q_beta_anue,Q_pair_nue_anue,Q_pair_nux_anux,Q_plasmon_nue_anue,Q_plasmon_nux_anux,Q_Brems_nui_anui;
  REAL R_eff_nue,R_eff_anue,Q_eff_nue,Q_eff_anue,Q_eff_nux;
  REAL kappa_s_n_0_nue,kappa_s_p_0_nue,kappa_a_0_nue,kappa_s_n_1_nue,kappa_s_p_1_nue,kappa_a_1_nue;
  REAL kappa_s_n_0_anue,kappa_s_p_0_anue,kappa_a_0_anue,kappa_s_n_1_anue,kappa_s_p_1_anue,kappa_a_1_anue;
  REAL kappa_s_n_0_nux,kappa_s_p_0_nux,kappa_s_n_1_nux,kappa_s_p_1_nux;
  const REAL tmp_0 = (1.0/(T));
  const REAL tmp_1 = mu_e*tmp_0;
  const REAL tmp_2 = NRPyLeakage_Fermi_Dirac_integrals(4, tmp_1);
  const REAL tmp_3 = ((NRPyLeakage_alpha)*(NRPyLeakage_alpha));
  const REAL tmp_5 = 8*M_PI*NRPyLeakage_N_A*NRPyLeakage_beta*rho_b_cgs*((3.0/8.0)*tmp_3 + 1.0/8.0)/NRPyLeakage_hc3;
  const REAL tmp_6 = ((T)*(T)*(T)*(T)*(T))*tmp_5;
  const REAL tmp_7 = NRPyLeakage_Fermi_Dirac_integrals(5, tmp_1);
  const REAL tmp_9 = -muhat*tmp_0 + tmp_1;
  const REAL tmp_10 = NRPyLeakage_enable_beta_nue*Y_pn/(exp(tmp_9 - tmp_7/tmp_2) + 1);
  const REAL tmp_11 = tmp_10*tmp_2*tmp_6;
  const REAL tmp_13 = NRPyLeakage_Fermi_Dirac_integrals(4, -tmp_1);
  const REAL tmp_14 = NRPyLeakage_Fermi_Dirac_integrals(5, -tmp_1);
  const REAL tmp_15 = muhat*tmp_0 - tmp_1;
  const REAL tmp_16 = NRPyLeakage_enable_beta_anue*Y_np/(exp(tmp_15 - tmp_14/tmp_13) + 1);
  const REAL tmp_17 = tmp_13*tmp_16*tmp_6;
  const REAL tmp_18 = NRPyLeakage_Fermi_Dirac_integrals(3, tmp_1);
  const REAL tmp_19 = NRPyLeakage_Fermi_Dirac_integrals(3, -tmp_1);
  const REAL tmp_20 = -1.0/2.0*tmp_13/tmp_19 - 1.0/2.0*tmp_2/tmp_18;
  const REAL tmp_21 = NRPyLeakage_C1pC2_nue_anue*NRPyLeakage_enable_pair_nue_anue/((exp(tmp_15 + tmp_20) + 1)*(exp(tmp_20 + tmp_9) + 1));
  const REAL tmp_22 = ((M_PI)*(M_PI));
  const REAL tmp_24 = (1.0/((NRPyLeakage_hc3)*(NRPyLeakage_hc3)));
  const REAL tmp_25 = NRPyLeakage_beta*pow(T, 8)*tmp_24;
  const REAL tmp_26 = (16.0/9.0)*tmp_18*tmp_19*tmp_22*tmp_25;
  const REAL tmp_28 = NRPyLeakage_C1pC2_nux_anux*NRPyLeakage_enable_pair_nux_anux/((exp(tmp_20) + 1)*(exp(tmp_20) + 1));
  const REAL tmp_30 = (1.0/3.0)*tmp_22 + ((mu_e)*(mu_e))/((T)*(T));
  const REAL tmp_31 = NRPyLeakage_gamma_0*sqrt(tmp_30);
  const REAL tmp_33 = ((M_PI)*(M_PI)*(M_PI))*pow(NRPyLeakage_gamma_0, 6)*((tmp_30)*(tmp_30)*(tmp_30))*(tmp_31 + 1)*exp(-tmp_31)/NRPyLeakage_alpha_fs;
  const REAL tmp_34 = (1.0/3.0)*tmp_25*tmp_33;
  const REAL tmp_35 = ((NRPyLeakage_gamma_0)*(NRPyLeakage_gamma_0))*tmp_30/(tmp_31 + 1);
  const REAL tmp_36 = -1.0/2.0*tmp_35 - 1;
  const REAL tmp_37 = ((NRPyLeakage_C_V)*(NRPyLeakage_C_V))*NRPyLeakage_enable_plasmon_nue_anue/((exp(tmp_15 + tmp_36) + 1)*(exp(tmp_36 + tmp_9) + 1));
  const REAL tmp_39 = ((NRPyLeakage_C_V - 1)*(NRPyLeakage_C_V - 1));
  const REAL tmp_40 = NRPyLeakage_enable_plasmon_nux_anux/((exp(tmp_36) + 1)*(exp(tmp_36) + 1));
  const REAL tmp_41 = NRPyLeakage_Brems_zeta*NRPyLeakage_enable_brems_nui_anui*rho_b_cgs*(((X_n)*(X_n)) + (28.0/3.0)*X_n*X_p + ((X_p)*(X_p)));
  const REAL tmp_42 = NRPyLeakage_Brems_C1*pow(T, 4.5)*tmp_41;
  const REAL tmp_43 = pow(T, 6)*tmp_5;
  const REAL tmp_44 = tmp_10*tmp_43*tmp_7;
  const REAL tmp_45 = tmp_14*tmp_16*tmp_43;
  const REAL tmp_46 = pow(T, 9)*tmp_24;
  const REAL tmp_48 = (1.0/36.0)*NRPyLeakage_beta*(32*tmp_13*tmp_18*tmp_22*tmp_46 + 32*tmp_19*tmp_2*tmp_22*tmp_46);
  const REAL tmp_51 = NRPyLeakage_beta*tmp_33*tmp_46*(tmp_35 + 2);
  const REAL tmp_52 = (1.0/6.0)*tmp_37*tmp_51;
  const REAL tmp_54 = (1.0/6.0)*tmp_39*tmp_40*tmp_51;
  const REAL tmp_55 = NRPyLeakage_Brems_C2*pow(T, 5.5)*tmp_41;
  const REAL tmp_56 = tmp_21*tmp_26 + tmp_34*tmp_37 + tmp_42;
  const REAL tmp_58 = (1.0/(NRPyLeakage_Fermi_Dirac_integrals(2, tmp_9)));
  const REAL tmp_59 = NRPyLeakage_Fermi_Dirac_integrals(4, tmp_9);
  const REAL tmp_60 = NRPyLeakage_N_A*NRPyLeakage_sigma_0*((T)*(T))*rho_b_cgs/((NRPyLeakage_m_e_c2)*(NRPyLeakage_m_e_c2));
  const REAL tmp_61 = tmp_58*tmp_59*tmp_60;
  const REAL // Not supported in C:
// MAX
tmp_63 = (1 - Y_e)*((5.0/24.0)*tmp_3 + 1.0/24.0)/((2.0/3.0)*MAX(mu_n*tmp_0, 0) + 1);
  const REAL // Not supported in C:
// MAX
tmp_65 = Y_e*((5.0/24.0)*tmp_3 + (1.0/6.0)*tmp_39)/((2.0/3.0)*MAX(mu_p*tmp_0, 0) + 1);
  const REAL tmp_67 = NRPyLeakage_Fermi_Dirac_integrals(5, tmp_9);
  const REAL tmp_68 = (3.0/4.0)*tmp_3 + 1.0/4.0;
  const REAL tmp_69 = Y_np*tmp_68/(exp(tmp_1 - tmp_67/tmp_59) + 1);
  const REAL tmp_71 = tmp_61*tmp_63 + tmp_61*tmp_65 + tmp_61*tmp_69;
  const REAL tmp_72 = (3.0/2.0)*NRPyLeakage_hc3/(M_PI*NRPyLeakage_units_geom_to_cgs_L);
  const REAL tmp_73 = tmp_72/((T)*(T)*(T));
  const REAL tmp_74 = (tmp_11 + tmp_56)/(((tau_nue[0])*(tau_nue[0]))*tmp_58*tmp_73*(tmp_11 + tmp_56)/tmp_71 + 1);
  const REAL tmp_76 = (1.0/(NRPyLeakage_Fermi_Dirac_integrals(2, tmp_15)));
  const REAL tmp_77 = NRPyLeakage_Fermi_Dirac_integrals(4, tmp_15);
  const REAL tmp_79 = tmp_60*tmp_76*tmp_77;
  const REAL tmp_81 = tmp_60*tmp_65;
  const REAL tmp_82 = tmp_76*tmp_77*tmp_81;
  const REAL tmp_83 = NRPyLeakage_Fermi_Dirac_integrals(5, tmp_15);
  const REAL tmp_84 = Y_pn*tmp_68/(exp(-tmp_1 - tmp_83/tmp_77) + 1);
  const REAL tmp_86 = tmp_63*tmp_79 + tmp_79*tmp_84 + tmp_82;
  const REAL tmp_87 = (tmp_17 + tmp_56)/(((tau_anue[0])*(tau_anue[0]))*tmp_73*tmp_76*(tmp_17 + tmp_56)/tmp_86 + 1);
  const REAL tmp_88 = tmp_21*tmp_48 + tmp_52 + tmp_55;
  const REAL tmp_90 = (1.0/(NRPyLeakage_Fermi_Dirac_integrals(3, tmp_9)));
  const REAL tmp_92 = tmp_60*tmp_67*tmp_90;
  const REAL tmp_94 = tmp_67*tmp_81*tmp_90;
  const REAL tmp_96 = tmp_63*tmp_92 + tmp_69*tmp_92 + tmp_94;
  const REAL tmp_97 = tmp_72/((T)*(T)*(T)*(T));
  const REAL tmp_98 = tmp_97*(tmp_44 + tmp_88);
  const REAL tmp_99 = (tmp_44 + tmp_88)/(((tau_nue[1])*(tau_nue[1]))*tmp_90*tmp_98/tmp_96 + 1);
  const REAL tmp_101 = (1.0/(NRPyLeakage_Fermi_Dirac_integrals(3, tmp_15)));
  const REAL tmp_103 = tmp_101*tmp_60*tmp_83;
  const REAL tmp_105 = tmp_101*tmp_81*tmp_83;
  const REAL tmp_107 = tmp_103*tmp_63 + tmp_103*tmp_84 + tmp_105;
  const REAL tmp_108 = (tmp_45 + tmp_88)/(((tau_anue[1])*(tau_anue[1]))*tmp_101*tmp_97*(tmp_45 + tmp_88)/tmp_107 + 1);
  const REAL tmp_109 = (1.0/(NRPyLeakage_Fermi_Dirac_integrals(3, 0)));
  const REAL tmp_110 = tmp_109*NRPyLeakage_Fermi_Dirac_integrals(5, 0);
  const REAL tmp_112 = tmp_110*tmp_60*tmp_63;
  const REAL tmp_114 = tmp_110*tmp_81 + tmp_112;
  const REAL tmp_115 = (tmp_28*tmp_48 + tmp_54 + tmp_55)/(((tau_nux[1])*(tau_nux[1]))*tmp_109*tmp_98/tmp_114 + 1);
  const REAL tmp_116 = NRPyLeakage_Fermi_Dirac_integrals(4, 0)/NRPyLeakage_Fermi_Dirac_integrals(2, 0);
  const REAL tmp_117 = tmp_116*tmp_60*tmp_63;
  R_beta_nue = tmp_11;
  R_beta_anue = tmp_17;
  R_pair_nue_anue = tmp_21*tmp_26;
  R_pair_nux_anux = tmp_26*tmp_28;
  R_plasmon_nue_anue = tmp_34*tmp_37;
  R_plasmon_nux_anux = tmp_34*tmp_39*tmp_40;
  R_Brems_nui_anui = tmp_42;
  Q_beta_nue = tmp_44;
  Q_beta_anue = tmp_45;
  Q_pair_nue_anue = tmp_21*tmp_48;
  Q_pair_nux_anux = tmp_28*tmp_48;
  Q_plasmon_nue_anue = tmp_52;
  Q_plasmon_nux_anux = tmp_54;
  Q_Brems_nui_anui = tmp_55;
  R_eff_nue = tmp_74;
  R_eff_anue = tmp_87;
  Q_eff_nue = tmp_99;
  Q_eff_anue = tmp_108;
  Q_eff_nux = tmp_115;
  kappa_s_n_0_nue = tmp_61*tmp_63;
  kappa_s_p_0_nue = tmp_61*tmp_65;
  kappa_a_0_nue = tmp_61*tmp_69;
  kappa_s_n_1_nue = tmp_63*tmp_92;
  kappa_s_p_1_nue = tmp_94;
  kappa_a_1_nue = tmp_69*tmp_92;
  kappa_s_n_0_anue = tmp_63*tmp_79;
  kappa_s_p_0_anue = tmp_82;
  kappa_a_0_anue = tmp_79*tmp_84;
  kappa_s_n_1_anue = tmp_103*tmp_63;
  kappa_s_p_1_anue = tmp_105;
  kappa_a_1_anue = tmp_103*tmp_84;
  kappa_s_n_0_nux = tmp_117;
  kappa_s_p_0_nux = tmp_116*tmp_81;
  kappa_s_n_1_nux = tmp_112;
  kappa_s_p_1_nux = tmp_110*tmp_81;
  *R_source = NRPyLeakage_amu*NRPyLeakage_units_cgs_to_geom_R*(-tmp_74 + tmp_87);
  *Q_source = NRPyLeakage_units_cgs_to_geom_Q*(-tmp_108 - 4*tmp_115 - tmp_99);
  kappa_nue[0] = NRPyLeakage_units_geom_to_cgs_L*tmp_71;
  kappa_nue[1] = NRPyLeakage_units_geom_to_cgs_L*tmp_96;
  kappa_anue[0] = NRPyLeakage_units_geom_to_cgs_L*tmp_86;
  kappa_anue[1] = NRPyLeakage_units_geom_to_cgs_L*tmp_107;
  kappa_nux[0] = NRPyLeakage_units_geom_to_cgs_L*(tmp_116*tmp_81 + tmp_117);
  kappa_nux[1] = NRPyLeakage_units_geom_to_cgs_L*tmp_114;
  fprintf(stderr,"(NRPyLeakage) R_beta_nue         = %.15e\n",R_beta_nue);
  fprintf(stderr,"(NRPyLeakage) R_beta_anue        = %.15e\n",R_beta_anue);
  fprintf(stderr,"(NRPyLeakage) R_pair_nue_anue    = %.15e\n",R_pair_nue_anue);
  fprintf(stderr,"(NRPyLeakage) R_pair_nux_anux    = %.15e\n",R_pair_nux_anux);
  fprintf(stderr,"(NRPyLeakage) R_plasmon_nue_anue = %.15e\n",R_plasmon_nue_anue);
  fprintf(stderr,"(NRPyLeakage) R_plasmon_nux_anux = %.15e\n",R_plasmon_nux_anux);
  fprintf(stderr,"(NRPyLeakage) R_Brems_nui_anui   = %.15e\n",R_Brems_nui_anui);
  fprintf(stderr,"(NRPyLeakage) Q_beta_nue         = %.15e\n",Q_beta_nue);
  fprintf(stderr,"(NRPyLeakage) Q_beta_anue        = %.15e\n",Q_beta_anue);
  fprintf(stderr,"(NRPyLeakage) Q_pair_nue_anue    = %.15e\n",Q_pair_nue_anue);
  fprintf(stderr,"(NRPyLeakage) Q_pair_nux_anux    = %.15e\n",Q_pair_nux_anux);
  fprintf(stderr,"(NRPyLeakage) Q_plasmon_nue_anue = %.15e\n",Q_plasmon_nue_anue);
  fprintf(stderr,"(NRPyLeakage) Q_plasmon_nux_anux = %.15e\n",Q_plasmon_nux_anux);
  fprintf(stderr,"(NRPyLeakage) Q_Brems_nui_anui   = %.15e\n",Q_Brems_nui_anui);
  fprintf(stderr,"(NRPyLeakage) R_eff_nue          = %.15e\n",R_eff_nue);
  fprintf(stderr,"(NRPyLeakage) R_eff_anue         = %.15e\n",R_eff_anue);
  fprintf(stderr,"(NRPyLeakage) Q_eff_nue          = %.15e\n",Q_eff_nue);
  fprintf(stderr,"(NRPyLeakage) Q_eff_anue         = %.15e\n",Q_eff_anue);
  fprintf(stderr,"(NRPyLeakage) Q_eff_nux          = %.15e\n",Q_eff_nux);
  fprintf(stderr,"(NRPyLeakage) kappa_s_n_0_nue    = %.15e\n",kappa_s_n_0_nue);
  fprintf(stderr,"(NRPyLeakage) kappa_s_p_0_nue    = %.15e\n",kappa_s_p_0_nue);
  fprintf(stderr,"(NRPyLeakage) kappa_a_0_nue      = %.15e\n",kappa_a_0_nue);
  fprintf(stderr,"(NRPyLeakage) kappa_s_n_1_nue    = %.15e\n",kappa_s_n_1_nue);
  fprintf(stderr,"(NRPyLeakage) kappa_s_p_1_nue    = %.15e\n",kappa_s_p_1_nue);
  fprintf(stderr,"(NRPyLeakage) kappa_a_1_nue      = %.15e\n",kappa_a_1_nue);
  fprintf(stderr,"(NRPyLeakage) kappa_s_n_0_anue   = %.15e\n",kappa_s_n_0_anue);
  fprintf(stderr,"(NRPyLeakage) kappa_s_p_0_anue   = %.15e\n",kappa_s_p_0_anue);
  fprintf(stderr,"(NRPyLeakage) kappa_a_0_anue     = %.15e\n",kappa_a_0_anue);
  fprintf(stderr,"(NRPyLeakage) kappa_s_n_1_anue   = %.15e\n",kappa_s_n_1_anue);
  fprintf(stderr,"(NRPyLeakage) kappa_s_p_1_anue   = %.15e\n",kappa_s_p_1_anue);
  fprintf(stderr,"(NRPyLeakage) kappa_a_1_anue     = %.15e\n",kappa_a_1_anue);
  fprintf(stderr,"(NRPyLeakage) kappa_s_n_0_nux    = %.15e\n",kappa_s_n_0_nux);
  fprintf(stderr,"(NRPyLeakage) kappa_s_p_0_nux    = %.15e\n",kappa_s_p_0_nux);
  fprintf(stderr,"(NRPyLeakage) kappa_s_n_1_nux    = %.15e\n",kappa_s_n_1_nux);
  fprintf(stderr,"(NRPyLeakage) kappa_s_p_1_nux    = %.15e\n",kappa_s_p_1_nux);
  fprintf(stderr,"(NRPyLeakage) *R_source          = %.15e\n",*R_source);
  fprintf(stderr,"(NRPyLeakage) *Q_source          = %.15e\n",*Q_source);
  fprintf(stderr,"(NRPyLeakage) kappa_nue[0]       = %.15e\n",kappa_nue[0]);
  fprintf(stderr,"(NRPyLeakage) kappa_nue[1]       = %.15e\n",kappa_nue[1]);
  fprintf(stderr,"(NRPyLeakage) kappa_anue[0]      = %.15e\n",kappa_anue[0]);
  fprintf(stderr,"(NRPyLeakage) kappa_anue[1]      = %.15e\n",kappa_anue[1]);
  fprintf(stderr,"(NRPyLeakage) kappa_nux[0]       = %.15e\n",kappa_nux[0]);
  fprintf(stderr,"(NRPyLeakage) kappa_nux[1]       = %.15e\n",kappa_nux[1]);
  fprintf(stderr,"(NRPyLeakage) ************************************************\n");
}
